name: web deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: deploy tomcat
      run: curl -v -u manager:admin -T /home/runner/work/mvn-hello-world/mvn-hello-world/target/jb-hello-world-maven-0.1.0.jar 'http://ec2-52-66-214-26.ap-south-1.compute.amazonaws.com:8080//manager/text/deploy?path=/my_rrt'
